export default {
  runtime: "Runtime",
  "runtime.getStarted": "Welcome to Bun",
  "runtime.coreRuntime": "Core Runtime",
  "runtime.File&ModuleSystem": "File & Module System",
  "runtime.httpServer": "HTTP Server",
  "runtime.Networking": "Networking",
  "runtime.data&Storage": "Data & Storage",
  "runtime.concurrency": "Concurrency",
  "runtime.process&System": "Process & System",
  "runtime.interop&Tooling": "Interop & Tooling",
  "runtime.utilities": "Utilities",
  "runtime.standards&Compatibility": "Standards & Compatibility",
  "runtime.contributing": "Contributing",

  packageManager: "Package Manager",
  "packageManager.coreCommands": "Core Commands",
  "packageManager.publishing&Analysis": "Publishing & Analysis",
  "packageManager.workspaceManagement": "Workspace Management",
  "packageManager.advancedConfiguration": "Advanced Configuration",

  bundler: "Bundler",
  "bundler.core": "Core",
  "bundler.developmentServer": "Development Server",
  "bundler.assetProcessing": "Asset Processing",
  "bundler.singleFileExecutable": "Single File Executable",
  "bundler.extensions": "Extensions",
  "bundler.optimization": "Optimization",
  "bundler.migration": "Migration",

  testRunner: "Test Runner",
  "testRunner.gettingStarted": "Getting Started",
  "testRunner.testExecution": "Test Execution",
  "testRunner.testFeatures": "Test Features",
  "testRunner.specializedTesting": "Specialized Testing",
  "testRunner.reporting": "Reporting",
};
